# iris資料集介紹：

In [1]:
from keras.utils import np_utils
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()
iris

Using TensorFlow backend.


{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

## 簡介資料集內容、類別
## 每筆資料那些特徵值(features)或屬性(attributes)。

資料集內容：150朵花的特徵值(sepal length, sepal width, petal length, petal width)

類別：150朵花的屬性('setosa', 'versicolor', 'virginica')


# 資料預處理(data preprocessing)

In [12]:
a=np.random.permutation(150)
b=np.random.permutation(125)
x_train_data=iris.data[a]
y_train_label=iris.target[a]
x_test_data=iris.data[b]
y_test_label=iris.target[b]

In [13]:
print(x_test_data)

[[4.5 2.3 1.3 0.3]
 [5.4 3.7 1.5 0.2]
 [5.7 4.4 1.5 0.4]
 [4.9 2.5 4.5 1.7]
 [5.7 2.9 4.2 1.3]
 [5.4 3.9 1.7 0.4]
 [5.  3.3 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.6 2.5 3.9 1.1]
 [6.2 2.9 4.3 1.3]
 [6.1 2.9 4.7 1.4]
 [6.3 3.3 6.  2.5]
 [5.8 2.8 5.1 2.4]
 [5.6 2.7 4.2 1.3]
 [4.7 3.2 1.3 0.2]
 [4.8 3.4 1.9 0.2]
 [5.5 3.5 1.3 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.4 1.6 0.4]
 [5.5 2.6 4.4 1.2]
 [4.6 3.4 1.4 0.3]
 [5.8 2.7 4.1 1. ]
 [6.  2.2 4.  1. ]
 [6.1 2.8 4.  1.3]
 [4.7 3.2 1.6 0.2]
 [6.3 2.3 4.4 1.3]
 [5.  3.6 1.4 0.2]
 [6.1 3.  4.6 1.4]
 [6.4 3.2 5.3 2.3]
 [5.  3.5 1.6 0.6]
 [6.3 2.5 4.9 1.5]
 [7.1 3.  5.9 2.1]
 [6.4 2.9 4.3 1.3]
 [5.4 3.4 1.7 0.2]
 [5.  2.3 3.3 1. ]
 [5.6 3.  4.1 1.3]
 [5.2 3.4 1.4 0.2]
 [5.9 3.  4.2 1.5]
 [4.6 3.1 1.5 0.2]
 [6.4 3.2 4.5 1.5]
 [5.4 3.  4.5 1.5]
 [4.8 3.1 1.6 0.2]
 [4.4 3.  1.3 0.2]
 [7.7 2.8 6.7 2. ]
 [7.7 3.8 6.7 2.2]
 [6.6 2.9 4.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.8 2.7 5.1 1.9]
 [5.7 2.8 4.5 1.3]
 [4.4 2.9 1.4 0.2]
 [6.3 3.3 4.7 1.6]
 [5.7 3.  4.2 1.2]
 [6.8 3.  5.

In [21]:
print('x_train:',len(x_train_data),
      'x_test:',len(x_test_data),
      'y_train:',len(y_train_label),
      'y_test:',len(y_test_label)
     )

x_train: 150 x_test: 125 y_train: 150 y_test: 125


In [24]:
x_train =x_train_data.reshape(150, 4).astype('float32')
x_test = x_test_data.reshape(125, 4).astype('float32')

In [27]:
print(x_test)

[[4.5 2.3 1.3 0.3]
 [5.4 3.7 1.5 0.2]
 [5.7 4.4 1.5 0.4]
 [4.9 2.5 4.5 1.7]
 [5.7 2.9 4.2 1.3]
 [5.4 3.9 1.7 0.4]
 [5.  3.3 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.6 2.5 3.9 1.1]
 [6.2 2.9 4.3 1.3]
 [6.1 2.9 4.7 1.4]
 [6.3 3.3 6.  2.5]
 [5.8 2.8 5.1 2.4]
 [5.6 2.7 4.2 1.3]
 [4.7 3.2 1.3 0.2]
 [4.8 3.4 1.9 0.2]
 [5.5 3.5 1.3 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.4 1.6 0.4]
 [5.5 2.6 4.4 1.2]
 [4.6 3.4 1.4 0.3]
 [5.8 2.7 4.1 1. ]
 [6.  2.2 4.  1. ]
 [6.1 2.8 4.  1.3]
 [4.7 3.2 1.6 0.2]
 [6.3 2.3 4.4 1.3]
 [5.  3.6 1.4 0.2]
 [6.1 3.  4.6 1.4]
 [6.4 3.2 5.3 2.3]
 [5.  3.5 1.6 0.6]
 [6.3 2.5 4.9 1.5]
 [7.1 3.  5.9 2.1]
 [6.4 2.9 4.3 1.3]
 [5.4 3.4 1.7 0.2]
 [5.  2.3 3.3 1. ]
 [5.6 3.  4.1 1.3]
 [5.2 3.4 1.4 0.2]
 [5.9 3.  4.2 1.5]
 [4.6 3.1 1.5 0.2]
 [6.4 3.2 4.5 1.5]
 [5.4 3.  4.5 1.5]
 [4.8 3.1 1.6 0.2]
 [4.4 3.  1.3 0.2]
 [7.7 2.8 6.7 2. ]
 [7.7 3.8 6.7 2.2]
 [6.6 2.9 4.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.8 2.7 5.1 1.9]
 [5.7 2.8 4.5 1.3]
 [4.4 2.9 1.4 0.2]
 [6.3 3.3 4.7 1.6]
 [5.7 3.  4.2 1.2]
 [6.8 3.  5.

In [30]:
x_train_normalize = x_train_data / 8
x_test_normalize = x_test_data / 8


In [31]:
print(x_test_normalize)

[[0.5625 0.2875 0.1625 0.0375]
 [0.675  0.4625 0.1875 0.025 ]
 [0.7125 0.55   0.1875 0.05  ]
 [0.6125 0.3125 0.5625 0.2125]
 [0.7125 0.3625 0.525  0.1625]
 [0.675  0.4875 0.2125 0.05  ]
 [0.625  0.4125 0.175  0.025 ]
 [0.625  0.4375 0.1625 0.0375]
 [0.7    0.3125 0.4875 0.1375]
 [0.775  0.3625 0.5375 0.1625]
 [0.7625 0.3625 0.5875 0.175 ]
 [0.7875 0.4125 0.75   0.3125]
 [0.725  0.35   0.6375 0.3   ]
 [0.7    0.3375 0.525  0.1625]
 [0.5875 0.4    0.1625 0.025 ]
 [0.6    0.425  0.2375 0.025 ]
 [0.6875 0.4375 0.1625 0.025 ]
 [0.6625 0.4625 0.1875 0.025 ]
 [0.625  0.425  0.2    0.05  ]
 [0.6875 0.325  0.55   0.15  ]
 [0.575  0.425  0.175  0.0375]
 [0.725  0.3375 0.5125 0.125 ]
 [0.75   0.275  0.5    0.125 ]
 [0.7625 0.35   0.5    0.1625]
 [0.5875 0.4    0.2    0.025 ]
 [0.7875 0.2875 0.55   0.1625]
 [0.625  0.45   0.175  0.025 ]
 [0.7625 0.375  0.575  0.175 ]
 [0.8    0.4    0.6625 0.2875]
 [0.625  0.4375 0.2    0.075 ]
 [0.7875 0.3125 0.6125 0.1875]
 [0.8875 0.375  0.7375 0.2625]
 [0.8   

In [29]:
y_train_OneHot = np_utils.to_categorical(y_train_label)
y_test_OneHot = np_utils.to_categorical(y_test_label)

In [32]:
print(y_test_OneHot)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

# 建立模型

In [33]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [34]:
model = Sequential()

In [39]:
model.add(Dense(units=600, 
                input_dim=4, 
                kernel_initializer='normal', 
                activation='relu'))

In [40]:
model.add(Dropout(0.5))

In [41]:
model.add(Dense(units=3, 
                kernel_initializer='normal', 
                activation='softmax'))

In [42]:
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 150)               750       
_________________________________________________________________
dropout_1 (Dropout)          (None, 150)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 3)                 453       
_________________________________________________________________
dense_3 (Dense)              (None, 600)               2400      
_________________________________________________________________
dropout_2 (Dropout)          (None, 600)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 1803      
Total params: 5,406
Trainable params: 5,406
Non-trainable params: 0
_________________________________________________________________
None


# 訓練模型

In [43]:
model.compile(loss='categorical_crossentropy', 
              optimizer='adam', metrics=['accuracy'])

In [44]:
train_history=model.fit(x=x_train_normalize,
                        y=y_train_OneHot,validation_split=0.2, 
                        epochs=10, batch_size=10,verbose=2)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where



Train on 120 samples, validate on 30 samples
Epoch 1/10





 - 1s - loss: 1.0991 - acc: 0.3833 - val_loss: 1.1014 - val_acc: 0.3333
Epoch 2/10
 - 0s - loss: 1.0980 - acc: 0.3917 - val_loss: 1.1012 - val_acc: 0.3333
Epoch 3/10
 - 0s - loss: 1.0968 - acc: 0.3750 - val_loss: 1.1034 - val_acc: 0.2667
Epoch 4/10
 - 0s - loss: 1.0996 - acc: 0.3333 - val_loss: 1.0996 - val_acc: 0.2667
Epoch 5/10
 - 0s - loss: 1.0936 - acc: 0.3500 - val_loss: 1.0973 - val_acc: 0.2667
Epoch 6/10
 - 0s - loss: 1.0873 - acc: 0.3917 - val_loss: 1.0882 - val_acc: 0.2667
Epoch 7/10
 - 0s - loss: 1.0789 - acc: 0.4417 - val_loss: 1.0726 - val_acc: 0.2667
Epoch 8/10
 - 0s - loss: 1.0542 - acc: 0.5250 - val_loss: 1.0374 - val_acc: 0.5000
Epoch 9/10
 - 0s - loss: 1.0149 - acc: 0.7250 - val_loss: 0.9778 - val_acc: 0.9333
Epoch 10/10
 - 0s - loss: 0.9415 - acc: 0.8250 - val_loss: 0.8788 - val_acc: 0.9000
